/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_guz_filemanager_service_FileSystemService */

#ifndef _Included_ua_guz_filemanager_service_FileSystemService
#define _Included_ua_guz_filemanager_service_FileSystemService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_guz_filemanager_service_FileSystemService
 * Method:    countFiles
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ua_guz_filemanager_service_FileSystemService_countFiles
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ua_guz_filemanager_service_FileSystemService
 * Method:    countDirectories
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ua_guz_filemanager_service_FileSystemService_countDirectories
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ua_guz_filemanager_service_FileSystemService
 * Method:    getContent
 * Signature: (Ljava/lang/String;)[Lua/guz/filemanager/entity/FileSystemItem;
 */
JNIEXPORT jobjectArray JNICALL Java_ua_guz_filemanager_service_FileSystemService_getContent
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
